#!/bin/bash

# https://zvps.uk/ogame/
# http://ogame1304.de/epicblue/

mkdir -p default-skin
mkdir -p default-skin/gfx
mkdir -p default-skin/images
mkdir -p default-skin/img
mkdir -p default-skin/planeten/small
mkdir -p default-skin/gebaeude

cd default-skin
wget http://ogame1304.de/epicblue/index.html
wget http://ogame1304.de/epicblue/formate.css

cd default-skin/gfx
wget http://ogame1304.de/epicblue/gfx/info-help.jpg
wget http://ogame1304.de/epicblue/gfx/ogame-produktion.jpg
wget http://ogame1304.de/epicblue/gfx/user-menu.jpg


cd ../../
cd default-skin/images
wget http://ogame1304.de/epicblue/images/energie.gif
wget http://ogame1304.de/epicblue/images/deuterium.gif
wget http://ogame1304.de/epicblue/images/kristall.gif
wget http://ogame1304.de/epicblue/images/metall.gif

cd ../../
cd default-skin/planeten
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/dschjungelplanet10.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/eisplanet10.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/gasplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/normaltempplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/normaltempplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/normaltempplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/normaltempplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/normaltempplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/normaltempplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/normaltempplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/trockenplanet10.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/wasserplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/wuestenplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/wuestenplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/wuestenplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/wuestenplanet04.jpg

wget http://ogame1304.de/epicblue/planeten/mond.jpg
wget http://ogame1304.de/epicblue/planeten/debris.jpg


cd ../../
cd default-skin/planeten/small
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_dschjungelplanet10.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_eisplanet10.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_gasplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_normaltempplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_normaltempplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_normaltempplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_normaltempplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_normaltempplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_normaltempplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_normaltempplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_rockenplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_trockenplanet10.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet04.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet05.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet06.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet07.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet08.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet09.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wuestenplanet01.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wuestenplanet02.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wasserplanet03.jpg
wget http://ogame1304.de/epicblue/planeten/small/s_wuestenplanet04.jpg

cd ../../../
cd default-skin/img
wget http://ogame1304.de/epicblue/img/b.gif
wget http://ogame1304.de/epicblue/img/e.gif
wget http://ogame1304.de/epicblue/img/m.gif
wget http://ogame1304.de/epicblue/img/r.gif
wget http://ogame1304.de/epicblue/img/bg1.gif
wget http://ogame1304.de/epicblue/img/background.jpg

cd ../../
cd default-skin/gebaeude

wget http://ogame1304.de/epicblue/gebaeude/106.gif
wget http://ogame1304.de/epicblue/gebaeude/108.gif
wget http://ogame1304.de/epicblue/gebaeude/109.gif
wget http://ogame1304.de/epicblue/gebaeude/110.gif
wget http://ogame1304.de/epicblue/gebaeude/111.gif
wget http://ogame1304.de/epicblue/gebaeude/113.gif
wget http://ogame1304.de/epicblue/gebaeude/114.gif
wget http://ogame1304.de/epicblue/gebaeude/115.gif
wget http://ogame1304.de/epicblue/gebaeude/117.gif
wget http://ogame1304.de/epicblue/gebaeude/118.gif
wget http://ogame1304.de/epicblue/gebaeude/120.gif
wget http://ogame1304.de/epicblue/gebaeude/121.gif
wget http://ogame1304.de/epicblue/gebaeude/122.gif
wget http://ogame1304.de/epicblue/gebaeude/123.gif
wget http://ogame1304.de/epicblue/gebaeude/124.gif
wget http://ogame1304.de/epicblue/gebaeude/12.gif
wget http://ogame1304.de/epicblue/gebaeude/14.gif
wget http://ogame1304.de/epicblue/gebaeude/15.gif
wget http://ogame1304.de/epicblue/gebaeude/199.gif
wget http://ogame1304.de/epicblue/gebaeude/1.gif
wget http://ogame1304.de/epicblue/gebaeude/202.gif
wget http://ogame1304.de/epicblue/gebaeude/203.gif
wget http://ogame1304.de/epicblue/gebaeude/204.gif
wget http://ogame1304.de/epicblue/gebaeude/205.gif
wget http://ogame1304.de/epicblue/gebaeude/206.gif
wget http://ogame1304.de/epicblue/gebaeude/206.jpg
wget http://ogame1304.de/epicblue/gebaeude/207.gif
wget http://ogame1304.de/epicblue/gebaeude/208.gif
wget http://ogame1304.de/epicblue/gebaeude/209.gif
wget http://ogame1304.de/epicblue/gebaeude/210.gif
wget http://ogame1304.de/epicblue/gebaeude/211.gif
wget http://ogame1304.de/epicblue/gebaeude/212.gif
wget http://ogame1304.de/epicblue/gebaeude/213.gif
wget http://ogame1304.de/epicblue/gebaeude/214.gif
wget http://ogame1304.de/epicblue/gebaeude/215.gif
wget http://ogame1304.de/epicblue/gebaeude/21.gif
wget http://ogame1304.de/epicblue/gebaeude/22.gif
wget http://ogame1304.de/epicblue/gebaeude/23.gif
wget http://ogame1304.de/epicblue/gebaeude/24.gif
wget http://ogame1304.de/epicblue/gebaeude/2.gif
wget http://ogame1304.de/epicblue/gebaeude/31.gif
wget http://ogame1304.de/epicblue/gebaeude/33.gif
wget http://ogame1304.de/epicblue/gebaeude/34.gif
wget http://ogame1304.de/epicblue/gebaeude/3.gif
wget http://ogame1304.de/epicblue/gebaeude/401.gif
wget http://ogame1304.de/epicblue/gebaeude/402.gif
wget http://ogame1304.de/epicblue/gebaeude/403.gif
wget http://ogame1304.de/epicblue/gebaeude/404.gif
wget http://ogame1304.de/epicblue/gebaeude/405.gif
wget http://ogame1304.de/epicblue/gebaeude/406.gif
wget http://ogame1304.de/epicblue/gebaeude/407.gif
wget http://ogame1304.de/epicblue/gebaeude/408.gif
wget http://ogame1304.de/epicblue/gebaeude/41.gif
wget http://ogame1304.de/epicblue/gebaeude/42.gif
wget http://ogame1304.de/epicblue/gebaeude/43.gif
wget http://ogame1304.de/epicblue/gebaeude/44.gif
wget http://ogame1304.de/epicblue/gebaeude/4.gif
wget http://ogame1304.de/epicblue/gebaeude/501.gif
wget http://ogame1304.de/epicblue/gebaeude/502.gif
wget http://ogame1304.de/epicblue/gebaeude/503.gif